### ISSUE TITLE
Xcode gives me errors, parse issue, "expected a type", "unknown type name 'UICollectionView Layout'"...

### ISSUE THREAD

**Issue by zttt** [lukescott/DraggableCollectionView#45]
Project was created using Xcode 6, Deployment Target 8.0.
![1](https://cloud.githubusercontent.com/assets/8820946/4492936/66c9c5a8-4a45-11e4-91db-87c8ec6b20dc.png)

I tried create a new project using xcode 4.6.3, I worked fine. But when I imported those files to my xcode 6  project, it gives me errors. Does anybody know why?

**Comment by drost** [comment]
I had the same problem. What I found was that an import of UIKit.h was missing from LSCollectionViewLayoutHelper.h. So just add 
_#import <UIKit/UIKit.h>_
to the top of that file and your good to go.
The reason it works with the included example project is because it uses a prefix header containing that include. Was a bit tricky to find because of all the "random" errors.

**Comment by 03128crz** [comment]
cause xcode6 don't create pch file ,so you need to import <UIKit/UIkit.h>
