### ISSUE TITLE
Problem dragging in flowlayout when only 1 section

### ISSUE THREAD

**Issue by AndrewHartAR** [lukescott/DraggableCollectionView#5]
It took me a while to find the problem here.

If there's only 1 section, there's an additional, unwanted animation when dragging a cell to a new position, when you let go of the object. Every object which moves as part of the change  actually animates into it's new position, behind a copy of itself. It's difficult to explain, but if you start the flowlayout demo, and change SECTION_COUNT to 1, and then drag some cells around, you'll hopefully see what i mean.

**Comment by lukescott** [comment]
I see what you mean. It looks like this problem was introduced as a result of my last commit. Strange, this is something I would have noticed. Trying to find a fix that solves both problems. In the mean time if you roll back the last commit on your last copy that should work fo now, until I'm able to find a more permanent solution.

**Comment by lukescott** [comment]
This should fix the issue. Let me know.

**Comment by AndrewHartAR** [comment]
That's fixed it. Thanks, and great work :)
